name: itvlist

on:
  schedule:
    - cron: '0 15,21 * * *'
  push:
    branches:
      - bra
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Update pip
        run: python -m pip install --upgrade pip
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install aiohttp
          pip install selenium requests futures opencv-python eventlet
          sudo apt-get install ffmpeg
          

      - name: Install Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=120.0.6099.109
          curl -sS -o chromedriver_linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-headless-shell-linux64.zip"
          sudo unzip chromedriver_linux64.zip -d /usr/local/bin
          rm chromedriver_linux64.zip
      - name: Set chromedriver path
        run: |
          sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run itv
        run: python ${{ github.workspace }}/itv.py

      - name: Run itvtest
        run: python ${{ github.workspace }}/itvtest.py

      - name: Run hd
        run: python ${{ github.workspace }}/hd.py
        
        
      #- name: Upload a Build Artifact
        #uses: actions/upload-artifact@v4.0.0
        #with:
          #name: itv
          #path: ${{ github.workspace }}/



      - name: 提交更改
        run: |
          git config --local user.email "6fybq3a5@nqmo.com"
          git config --local user.name "o1il"
          git add .
          git commit -m "Add generated files"
          #git pull --rebase
          git push -f



      - name: 提交更改到主分支
        run: |
          git config --local user.email "6fybq3a5@nqmo.com"
          git config --local user.name "o1il"
          git fetch origin 0:0  
          git checkout 0
          git checkout bra -- 10001 10001m3u hyd hydm3u  
          git add 10001 10001m3u hyd hydm3u
          git commit -m "Add files from bra branch" || true  
          git push -f origin HEAD:refs/heads/0  
